// Generated by GPT (OpenAI)
// Validated by ryan

package proto;

import org.junit.jupiter.api.Test;

import java.io.*;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.StandardCharsets;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

final class PacketsTest {
    @Test
    void createRoom_hasOpcode_noTlvs() throws IOException {
        Packet p = Packets.createRoom();
        assertEquals(Op.CREATE_ROOM, p.opcode);
        assertTrue(p.tlvs.isEmpty());

        Packet r = roundTrip(p);
        assertEquals(Op.CREATE_ROOM, r.opcode);
        assertTrue(r.tlvs.isEmpty());
    }

    @Test
    void joinRoom_carriesRoomCode() throws IOException {
        Packet p = Packets.joinRoom("123456");
        assertEquals(Op.JOIN_ROOM, p.opcode);
        assertEquals("123456", p.getStr(T.ROOM_CODE));

        Packet r = roundTrip(p);
        assertEquals("123456", r.getStr(T.ROOM_CODE));
    }

    @Test
    void chatSend_setsContentLengthAndMessage_validates() throws IOException {
        Packet p = Packets.chatSend("hello");
        assertEquals(Op.CHAT_SEND, p.opcode);
        assertTrue(Packets.validateContentLen(p));
        assertEquals("hello", p.getStr(T.MESSAGE));
        assertEquals(5L, p.getU32(T.CONTENT_LEN));

        Packet r = roundTrip(p);
        assertTrue(Packets.validateContentLen(r));
        assertEquals("hello", r.getStr(T.MESSAGE));
        assertEquals(5L, r.getU32(T.CONTENT_LEN));
    }

    @Test
    void chatSend_validateContentLen_failsWhenTampered() {
        Packet p = Packets.chatSend("hi");
        // Tamper: replace CONTENT_LEN with wrong value
        p.tlvs.replaceAll(t -> t.type == T.CONTENT_LEN ? Packet.Tlv.ofU32(T.CONTENT_LEN, 999) : t);
        assertFalse(Packets.validateContentLen(p));
    }

    @Test
    void heartbeat_and_ack_roundTrip() throws IOException {
        Packet hb = Packets.heartbeat();
        Packet hbRt = roundTrip(hb);
        assertEquals(Op.HEARTBEAT, hbRt.opcode);

        long now = System.currentTimeMillis();
        Packet ack = Packets.heartbeatAck(now);
        Packet ackRt = roundTrip(ack);
        assertEquals(Op.HEARTBEAT_ACK, ackRt.opcode);
        assertEquals(now, ackRt.getU64(T.TIMESTAMPMS));
    }

    @Test
    void createRoomAck_joinRoomAck_uuidAndCode() throws IOException {
        UUID id = UUID.randomUUID();
        String code = "654321";

        Packet cr = Packets.createRoomAck(id, code);
        Packet crRt = roundTrip(cr);
        assertEquals(Op.CREATE_ROOM_ACK, crRt.opcode);
        UUID idOut1 = Packets.bytesToUuid(crRt.tlvs.stream()
            .filter(t -> t.type == T.ROOM_ID).findFirst().orElseThrow().value);
        assertEquals(id, idOut1);
        assertEquals(code, crRt.getStr(T.ROOM_CODE));

        Packet jr = Packets.joinRoomAck(id, code);
        Packet jrRt = roundTrip(jr);
        assertEquals(Op.JOIN_ROOM_ACK, jrRt.opcode);
        UUID idOut2 = Packets.bytesToUuid(jrRt.tlvs.stream()
            .filter(t -> t.type == T.ROOM_ID).findFirst().orElseThrow().value);
        assertEquals(id, idOut2);
        assertEquals(code, jrRt.getStr(T.ROOM_CODE));
    }

    @Test
    void chatBroadcast_containsUsernameMessageAndLength() throws IOException {
        Packet b = Packets.chatBroadcast("alice", "hey there");
        assertEquals(Op.CHAT_BROADCAST, b.opcode);
        assertEquals("alice", b.getStr(T.USERNAME));
        assertEquals("hey there", b.getStr(T.MESSAGE));
        assertTrue(Packets.validateContentLen(b));

        Packet rt = roundTrip(b);
        assertEquals("alice", rt.getStr(T.USERNAME));
        assertEquals("hey there", rt.getStr(T.MESSAGE));
        assertTrue(Packets.validateContentLen(rt));
    }

    @Test
    void userJoined_userLeft_haveUsername() throws IOException {
        Packet j = Packets.userJoined("bob");
        Packet jrt = roundTrip(j);
        assertEquals(Op.USER_JOINED, jrt.opcode);
        assertEquals("bob", jrt.getStr(T.USERNAME));

        Packet l = Packets.userLeft("bob");
        Packet lrt = roundTrip(l);
        assertEquals(Op.USER_LEFT, lrt.opcode);
        assertEquals("bob", lrt.getStr(T.USERNAME));
    }

    @Test
    void error_containsCodeAndReason() throws IOException {
        Packet e = Packets.error(404, "room not found");
        Packet ert = roundTrip(e);
        assertEquals(Op.ERROR, ert.opcode);
        assertEquals(404L, ert.getU32(T.ERROR_CODE));
        assertEquals("room not found", ert.getStr(T.REASON));
    }

    @Test
    void ioHelpers_writeAndRead() throws IOException {
        Packet p = Packets.joinRoom("777777");
        ByteArrayOutputStream bout = new ByteArrayOutputStream();
        Packets.write(bout, p);

        byte[] bytes = bout.toByteArray();
        assertEquals(Packet.MAGIC, ByteBuffer.wrap(bytes, 0, 4).order(ByteOrder.BIG_ENDIAN).getInt());

        Packet r = Packets.read(new ByteArrayInputStream(bytes));
        assertEquals(Op.JOIN_ROOM, r.opcode);
        assertEquals("777777", r.getStr(T.ROOM_CODE));
    }

    // helpers

    private static Packet roundTrip(Packet p) throws IOException {
        byte[] bytes = p.toBytes();
        return Packet.read(new ByteArrayInputStream(bytes));
    }
}
